### ISSUE TITLE
Cannot drag and drop

### ISSUE THREAD

**Issue by ingo916** [SanderRonde/Octoprint-Draggable-Files#3]
OctoPrint 1.6.1
Python 3.7.3
OctoPi 0.18.0

I was unable to drag and drop the files while using the 
Firefox browser from my Windows PC. Also was not able to do the same from my iPad. After plugin installation, once I try to drag a file Octoprint becomes unresponsive for a moment then I am unable to scroll the page.

https://user-images.githubusercontent.com/41309095/118849318-7ac72f00-b884-11eb-8c64-8d67d1b68469.mp4

**Comment by SanderRonde** [comment]
This should be fixed in version 1.0.4, which should be live now. Can you give it a try once you are able to install that version?

**Comment by SanderRonde** [comment]
Closing this issue since there's no response
