### ISSUE TITLE
Incompatible with some other plugins.

### ISSUE THREAD

**Issue by distnz** [SanderRonde/Octoprint-Draggable-Files#4]
Love the idea of this however ive found it incompatible with "Consolidated Tabs 1.0.1" and "Dashboard 1.18.2". It causes the theme to wig out, consolidated tab to not displayu anything and the Dashboard plugin only loads icons, at 200% and nothing else.

System info below:

browser.user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
connectivity.connection_check: 1.1.1.1:53
connectivity.connection_ok: true
connectivity.enabled: true
connectivity.online: true
connectivity.resolution_check: octoprint.org
connectivity.resolution_ok: true
env.hardware.cores: 4
env.hardware.freq: 1500
env.hardware.ram: 4013572096
env.os.bits: 32
env.os.id: linux
env.os.platform: linux
env.plugins.pi_support.model: Raspberry Pi 4 Model B Rev 1.1
env.plugins.pi_support.octopi_version: 0.17.0
env.plugins.pi_support.throttle_state: 0x0
env.python.pip: 21.1.1
env.python.version: 3.7.3
env.python.virtualenv: true
octoprint.safe_mode: false
octoprint.version: 1.6.1
printer.firmware: Marlin Ver 1.0.2
systeminfo.generator: systemapi

**Comment by SanderRonde** [comment]
Are you sure this has to do with this plugin? I tried the exact same plugin setup but had no issues whatsoever. These are also things the plugin doesn't really interact with in any way so I'd be surprised if it was this plugin. Could you maybe hit F12 and look if there are any errors in the developer console? That could be a reason for this to be happening.

**Comment by distnz** [comment]
Sure, I'll install it again once I'm home. Sorry those were the obvious 2 plugins that appeared broken as soon as I installed this one, but could be wrong. I had tried this one twice and as soon as it was installed it broke and as soon as I uninstalled it everything was back to normal, but again I'm happy to be wrong :) I'll give it another shot tonight and try and document it better.

**Comment by SanderRonde** [comment]
Thank you! It could also be that at the time you had version 1.0.2 installed which broke during loading. Maybe it somehow broke loading for other plugins as well and caused those isues. Right now 1.0.3 is out so that problem should be fixed.

**Comment by distnz** [comment]
Version is showing as 1.0.4 after trying again, but hey it seems to work now! Thanks!

**Comment by SanderRonde** [comment]
That'a great to hear. Thanks for testing it out for me again. I'll be closing the issue then.
