### ISSUE TITLE
Unable to check for updates

### ISSUE THREAD

**Issue by Taomyn** [SanderRonde/Octoprint-Draggable-Files#9]
OctoPrint, v1.8.x, is unable to check the plug-in for updates (I do know there aren't any)

![image](https://user-images.githubusercontent.com/4365929/198938285-d84ba04d-3d70-4362-ba51-6c8c86b5e2c1.png)

**Comment by SanderRonde** [comment]
Hmm not sure if this is related to this plugin or whether this is an issue with your installation. Could you maybe send me the relevant part of your logs?

**Comment by Taomyn** [comment]
This is what I can find:

```
2022-10-31 06:24:13,230 - octoprint.plugins.softwareupdate.version_checks.github_release - ERROR - GitHub API error: Not Found (HTTP 404)
2022-10-31 06:24:13,241 - octoprint.plugins.softwareupdate - WARNING - Could not check draggable_files for updates due to an API error: GitHub API error: Not Found (HTTP 404)
```

Do you know what the URL would be so I can trace it my end? I'm not having issues with others except for Arc Welder but I think that's another problem which the dev is aware of.

**Comment by SanderRonde** [comment]
It's defined [over here](https://github.com/SanderRonde/Octoprint-Draggable-Files/blob/eb5139b8434649e17d763a99d1ee6bd5b33d0f7f/octoprint_draggable_files/__init__.py#L36). I'm pretty sure the exact URL is composed somewhere by Octoprint itself. A bit more info about it [over here](https://docs.octoprint.org/en/master/bundledplugins/softwareupdate.html). Not entirely sure what process they're using but I assume they're just querying `https://github.com/SanderRonde/Octoprint-Draggable-Files/releases` or some variant of it.

**Comment by Taomyn** [comment]
HI, thanks for the info, I wasn't able to get anything more so out of curiosity I uninstalled, restarted, then re-installed and now it's fine. Go figure.

Anyway, this might help anyone in the future if they come across this weirdness.
